[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
monitor_port = /dev/ttyUSB0
monitor_rts = 0
monitor_dtr = 0

board_build.partitions = huge_app.csv

; ESSENCIAL: Garante que bibliotecas internas da ArduinoWebsockets encontrem o core do ESP32
lib_ldf_mode = deep+

; Adiciona paths de include do framework para resolver o erro de "WiFi.h"
build_flags =
    -I"${PROJECT_CORE_DIR}/packages/framework-arduinoespressif32/cores/esp32"
    -I"${PROJECT_CORE_DIR}/packages/framework-arduinoespressif32/libraries/WiFiClientSecure/src"
    -I"${PROJECT_CORE_DIR}/packages/framework-arduinoespressif32/libraries/HTTPClient/src"
    -I"${PROJECT_CORE_DIR}/packages/framework-arduinoespressif32/libraries/WiFi/src"

lib_deps = 
    WiFi
    WiFiClientSecure
    https://github.com/mathieucarbou/ESPAsyncWebServer.git
    https://github.com/mathieucarbou/AsyncTCP.git
    gilmaimon/ArduinoWebsockets @ ^0.5.3