[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200

build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

board_build.partitions = huge_app.csv

; LDF Mode "deep+" faz o PIO varrer todas as subpastas em busca de cabeçalhos
lib_ldf_mode = deep+

lib_deps = 
    WiFi
    https://github.com/mathieucarbou/ESPAsyncWebServer.git
    https://github.com/mathieucarbou/AsyncTCP.git

lib_ignore = 
    WebServer